name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: default
          MYSQL_ROOT_PASSWORD: admin
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12.0.2
      - name: Build with Maven
        run: mvn clean install --file pom.xml
      - uses: malathit/localstack-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
