name: Build job

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: default
          MYSQL_ROOT_PASSWORD: admin
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12.0.2
      - run: for sql_file in `ls src/main/resources/db/migration/*.sql`; do mysql -u root -padmin < $sql_file; done
      - name: Build with Maven
        run: mvn clean install --file pom.xml