name: Build job

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        image: mysql:8.0
        ports:
            3306:3306
        env:
            MYSQL_DATABASE: default
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - my-db:/var/lib/mysql
            - ./src/main/resources/db/migration/:/docker-entrypoint-initdb.d/

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12.0.2
      - name: Build with Maven
        run: mvn clean install --file pom.xml